# Generated by Django 5.1.4 on 2025-01-16 02:37

import payment_methods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, default='default_image.png', upload_to=payment_methods.models.path_coin_icon, verbose_name='Иконка')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Символ валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('currencies', models.ManyToManyField(related_name='payment_methods', to='payment_methods.currency', verbose_name='Поддерживаемые валюты')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
    ]
