# Generated by Django 5.1.4 on 2025-01-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000, max_digits=10, verbose_name='Макс. сумма в эквиваленте USD'),
        ),
        migrations.AddField(
            model_name='currency',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10, verbose_name='Мин. сумма в эквиваленте USD'),
        ),
        migrations.AddField(
            model_name='currency',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена в USD'),
        ),
    ]
