# Generated by Django 5.1.4 on 2025-01-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0004_currency_price_rub_alter_currency_max_amount_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='comm_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Комиссия(%)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='max_comm_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Максимальная комиссия(сумма)'),
        ),
    ]
