# Generated by Django 5.1.4 on 2025-01-21 06:17

import payment_methods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0005_paymentmethod_comm_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='comm_percent',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='max_comm_money',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, default='default_image.png', upload_to=payment_methods.models.path_payment_method_icon, verbose_name='Картинка'),
        ),
    ]
