# Generated by Django 5.1.4 on 2025-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0006_remove_paymentmethod_comm_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Абревиатура'),
        ),
    ]
