# Generated by Django 5.1.4 on 2025-01-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0007_paymentmethod_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='title',
        ),
    ]
