# Generated by Django 5.1.4 on 2025-01-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tg_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tg_username',
        ),
    ]
