# Generated by Django 5.1.4 on 2025-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coin_ticker',
            field=models.CharField(max_length=50, null=True, verbose_name='Tикер'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(max_length=50, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_code',
            field=models.CharField(max_length=3, null=True, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coin_name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
