# Generated by Django 5.1.4 on 2025-01-27 08:38

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coin_ticker_order_currency_order_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='foto_check',
            field=models.ImageField(blank=True, null=True, upload_to=orders.models.path_check_img, verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Кошелёк'),
        ),
    ]
