# Generated by Django 5.1.4 on 2025-01-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_foto_check_order_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coin_amount',
            field=models.DecimalField(decimal_places=8, max_digits=35, verbose_name='Количество'),
        ),
    ]
