# Generated by Django 5.1.4 on 2025-01-14 02:51

import coins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('ticker', models.CharField(max_length=255, unique=True, verbose_name='Тикер')),
                ('icon', models.ImageField(blank=True, default='coins/icons/default_image.png', upload_to=coins.models.path_coin_icon, verbose_name='Иконка')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ценв USD')),
                ('price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена RUB')),
                ('price_byn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена BYN')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=9, max_digits=5, verbose_name='Комиссия')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
            },
        ),
    ]
