# Generated by Django 5.1.4 on 2025-01-16 02:37

import coins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='icon',
            field=models.ImageField(blank=True, default='default_image.png', upload_to=coins.models.path_coin_icon, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена USD'),
        ),
    ]
