# Generated by Django 5.1.4 on 2025-01-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coin_icon_alter_coin_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_byn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Цена BYN'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Цена RUB'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Цена USD'),
        ),
    ]
