# Generated by Django 5.1.4 on 2025-01-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_coin_price_byn_alter_coin_price_rub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='coin',
            name='network_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10, verbose_name='Комиссия сети в USD'),
        ),
    ]
