# Generated by Django 5.1.4 on 2025-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_remove_coin_commission_rate_coin_network_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ticker',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тикер'),
        ),
    ]
